package blog.anirbanm.reset.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 04 13:28:10 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }


    /**
     * Returns the variable value for Bind_FirstName.
     * @return variable value for Bind_FirstName
     */
    public String getBind_FirstName() {
        return (String) ensureVariableManager().getVariableValue("Bind_FirstName");
    }

    /**
     * Sets <code>value</code> for variable Bind_FirstName.
     * @param value value to bind as Bind_FirstName
     */
    public void setBind_FirstName(String value) {
        ensureVariableManager().setVariableValue("Bind_FirstName", value);
    }

    /**
     * Returns the variable value for Bind_LastName.
     * @return variable value for Bind_LastName
     */
    public String getBind_LastName() {
        return (String) ensureVariableManager().getVariableValue("Bind_LastName");
    }

    /**
     * Sets <code>value</code> for variable Bind_LastName.
     * @param value value to bind as Bind_LastName
     */
    public void setBind_LastName(String value) {
        ensureVariableManager().setVariableValue("Bind_LastName", value);
    }

    /**
     * Returns the variable value for Bind_Email.
     * @return variable value for Bind_Email
     */
    public String getBind_Email() {
        return (String) ensureVariableManager().getVariableValue("Bind_Email");
    }

    /**
     * Sets <code>value</code> for variable Bind_Email.
     * @param value value to bind as Bind_Email
     */
    public void setBind_Email(String value) {
        ensureVariableManager().setVariableValue("Bind_Email", value);
    }

    /**
     * Returns the variable value for Bind_JobId.
     * @return variable value for Bind_JobId
     */
    public String getBind_JobId() {
        return (String) ensureVariableManager().getVariableValue("Bind_JobId");
    }

    /**
     * Sets <code>value</code> for variable Bind_JobId.
     * @param value value to bind as Bind_JobId
     */
    public void setBind_JobId(String value) {
        ensureVariableManager().setVariableValue("Bind_JobId", value);
    }
}

