package blog.anirbanm.reset.model.am;


import blog.anirbanm.reset.model.am.common.ResetVCModule;
import blog.anirbanm.reset.model.view.EmployeesVOImpl;

import java.util.ArrayList;
import java.util.Collection;

import oracle.jbo.Variable;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 04 13:32:24 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResetVCModuleImpl extends ApplicationModuleImpl implements ResetVCModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ResetVCModuleImpl() {
    }
    
    public Collection<Variable> getAllBindVariables(final String voInstance, final String vcName) {
        final ViewObjectImpl view = (ViewObjectImpl) findViewObject(voInstance);
        if (view != null) {
            final ViewCriteria vc = view.getViewCriteria(vcName);
            if (vc != null) {
                return vc.getAllBindVariables();
            }
        }
        return null;
    }
    
    public void executeEmptyRowSet(final String voInstance) {
        final ViewObjectImpl view = (ViewObjectImpl) findViewObject(voInstance);
        if (view != null) {
            view.executeEmptyRowSet();
        }
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public EmployeesVOImpl getEmployeesVO1() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO1");
    }

}

