package blog.anirbanm.reset.model.am.common;

import java.util.Collection;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Variable;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 04 14:04:45 IST 2018
// ---------------------------------------------------------------------
public interface ResetVCModule extends ApplicationModule {
    Collection<Variable> getAllBindVariables(String voInstance, String vcName);

    void executeEmptyRowSet(String voInstance);
}

